#!/usr/bin/env python3
"""
Power BI Query Execution Status Report - August 14, 2025
Final diagnostic update after 24+ hour monitoring
"""

import os
import sys
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def main():
    print("📋 POWER BI QUERY EXECUTION STATUS REPORT")
    print("=" * 70)
    print(f"🕐 Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("📅 Issue Duration: 24+ hours (since August 13, 2025)")
    print()
    
    print("🔍 CURRENT STATUS SUMMARY")
    print("-" * 40)
    print("✅ Service Principal Authentication: WORKING")
    print("✅ Workspace Access: WORKING")
    print("✅ Dataset Metadata Access: WORKING")
    print("❌ DAX Query Execution: FAILING")
    print("❌ SQL Query Execution: FAILING")
    print("❌ Capacity Accessibility: NOT VISIBLE")
    print()
    
    print("🆔 TEST RESULTS BY DATASET")
    print("-" * 40)
    print("📊 FIS-SEMANTIC-MODEL (3ed8f6b3-0a1d-4910-9d31-a9dd3f8f4007):")
    print("   • DAX Queries: ❌ HTTP 401 - PowerBINotAuthorizedException")
    print("   • SQL Queries: ❌ HTTP 401 - PowerBINotAuthorizedException")
    print("   • Diagnosis: Authorization/permission issue")
    print()
    print("📊 AdventureWorks (fc4d80c8-090e-4441-8336-217490bde820):")
    print("   • DAX Queries: ❌ HTTP 400 - DatasetExecuteQueriesError")
    print("   • SQL Queries: ❌ HTTP 400 - DatasetExecuteQueriesError")
    print("   • Diagnosis: Query execution feature disabled")
    print()
    
    print("🎯 REFINED DIAGNOSIS")
    print("-" * 30)
    print("The different error codes suggest multiple issues:")
    print()
    print("1. 🔐 CAPACITY/PERMISSION ISSUE (FIS dataset):")
    print("   • 401 errors indicate authorization problems")
    print("   • Capacity not accessible via user API")
    print("   • Service principal may lack dataset-level execute permissions")
    print()
    print("2. 🚫 TENANT SETTING ISSUE (AdventureWorks dataset):")
    print("   • 400 errors indicate feature not enabled")
    print("   • 'Dataset Execute Queries REST API' may be disabled")
    print("   • Affects all datasets in tenant")
    print()
    
    print("🔧 IMMEDIATE ACTIONS REQUIRED")
    print("-" * 40)
    print("👨‍💼 POWER BI ADMINISTRATOR TASKS:")
    print()
    print("1. 🏢 TENANT SETTINGS:")
    print("   • Navigate to Power BI Admin Portal > Tenant Settings")
    print("   • Find 'Dataset Execute Queries REST API'")
    print("   • ENABLE for appropriate security groups")
    print("   • Wait 15-30 minutes for propagation")
    print()
    print("2. 🏭 CAPACITY MANAGEMENT:")
    print("   • Verify FIS workspace capacity assignment")
    print("   • Ensure capacity is running and accessible")
    print("   • Check XMLA Endpoint = 'Read Write'")
    print()
    print("3. 🔑 SERVICE PRINCIPAL PERMISSIONS:")
    print("   • Add service principal to workspace as Member/Admin")
    print("   • Grant 'Execute Queries' permission at dataset level")
    print("   • Verify Azure AD app registration permissions")
    print()
    
    print("🧪 VERIFICATION TESTS")
    print("-" * 30)
    print("After admin changes, run these tests:")
    print()
    print("🔄 Check tenant setting effect:")
    print("   export POWERBI_DATASET_ID=fc4d80c8-090e-4441-8336-217490bde820")
    print("   python3 compare_dax_sql.py")
    print("   Expected: 400 errors should change to 200 success")
    print()
    print("🔄 Check capacity/permission fix:")
    print("   export POWERBI_DATASET_ID=3ed8f6b3-0a1d-4910-9d31-a9dd3f8f4007")
    print("   python3 compare_dax_sql.py")
    print("   Expected: 401 errors should change to 200 success")
    print()
    print("🔄 Monitor capacity status:")
    print("   python3 fabric_capacity_status.py")
    print("   Expected: Workspace capacity should appear in accessible list")
    print()
    
    print("📞 ESCALATION PATH")
    print("-" * 25)
    print("If admin actions don't resolve the issue:")
    print("• Microsoft Support Case: https://powerbi.microsoft.com/support/")
    print("• Include this diagnostic report and all test outputs")
    print("• Reference: Service Principal Query Execution - 401/400 Errors")
    print()
    
    print("📊 MONITORING SCHEDULE")
    print("-" * 30)
    print("After admin intervention:")
    print("• ⏰ Immediate: Test after each admin change")
    print("• ⏰ +15 min: Allow for tenant setting propagation")
    print("• ⏰ +30 min: Final verification of all functionality")
    print("• ⏰ +1 hour: Escalate if still not working")
    print()
    
    print("✅ SUCCESS CRITERIA")
    print("-" * 25)
    print("Issue resolved when ALL of the following are true:")
    print("• ✅ fabric_capacity_status.py shows workspace capacity")
    print("• ✅ AdventureWorks queries return 200 (not 400)")
    print("• ✅ FIS dataset queries return 200 (not 401)")
    print("• ✅ diagnostic_summary.py reports SUCCESS")
    print()
    
    print(f"⏰ Report completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("📋 Next update: After admin intervention")

if __name__ == "__main__":
    main()
