erDiagram
	FIS_CL_DETAIL_FACT }o--|| FIS_CUSTOMER_DIMENSION : CUSTOMER_KEY
	FIS_CL_DETAIL_FACT }o--|| FIS_CURRENCY_DIMENSION : CURRENCY_KEY
	FIS_CL_DETAIL_FACT }o--|| FIS_MONTH_DIMENSION : MONTH_ID
	FIS_CL_DETAIL_FACT }o--|| FIS_INVESTOR_DIMENSION : INVESTOR_KEY
	FIS_CL_DETAIL_FACT {
		int CUSTOMER_KEY
		int CURRENCY_KEY
		int MONTH_ID
		int INVESTOR_KEY
		numeric TOTAL_BALANCE
		numeric LIMIT_AMOUNT
		bool IS_NON_PERFORMING
	}
	FIS_CUSTOMER_DIMENSION {
		int CUSTOMER_KEY PK
		string CUSTOMER_ID
		string CUSTOMER_NAME
		string COUNTRY_DESCRIPTION
		string RISK_RATING_DESCRIPTION
	}
	FIS_CURRENCY_DIMENSION {
		int CURRENCY_KEY PK
		string FROM_CURRENCY_CODE
		string TO_CURRENCY_CODE
	}
	FIS_MONTH_DIMENSION {
		int MONTH_ID PK
		date PERIOD_END_DATE
		int YEAR_ID
	}
	FIS_INVESTOR_DIMENSION {
		int INVESTOR_KEY PK
		string INVESTOR_NAME
	}
